global using CommunityToolkit.Maui;
global using CommunityToolkit.Maui.Views;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.Logging;
global using System.Collections.ObjectModel;
global using ComandaApp.Pages;
global using ComandaApp.PageModels;
global using ComandaApp.Models;