services:
  - type: web
    name: comanda-web-app
    env: static
    rootDir: ComandaWebApp
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
